## Creating matrices

In [15]:
arr = [[1,2]]
arr

[[1, 2]]

In [16]:
import numpy as np
a = np.array(arr)
a

array([[1, 2]])

In [17]:
import torch
b = torch.Tensor(a)
b

tensor([[1., 2.]])

### Create matrices with default values

In [22]:
np.ones((2,2))
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [23]:
np.random.rand(2,2)
torch.rand(2,2)

tensor([[0.1257, 0.1331],
        [0.8481, 0.0670]])

### seeds for reproducability

#### Numpy

In [25]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [26]:
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [27]:
np.random.rand(2,2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

#### pytorch

In [28]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [29]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [33]:
torch.rand(2,2)

tensor([[0.6977, 0.8000],
        [0.1610, 0.2823]])

#### Seed for GPU is different

In [34]:
if torch.cuda.is_available():
    print ("CUDA available")
    torch.cuda.manual_seed_all(0)

CUDA available


## NUmpy to Torch bridge


#### Numpy to Torch

In [42]:
np_array = np.ones((2,2))
print (np_array)
print (type(np_array))
torch_tensor = torch.from_numpy(np_array)
print("\n")
print (torch_tensor)
print (type(torch_tensor))

[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
<class 'torch.Tensor'>


#### Torch to Numpy

In [44]:
torch_tensor = torch.ones(2,2)
print (torch_tensor)
print(type(torch_tensor))
print ("\n")
np_array = torch_tensor.numpy()
print (np_array)
print (type(np_array))

tensor([[1., 1.],
        [1., 1.]])
<class 'torch.Tensor'>


[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


## Tensors on GPU vs CPU

In [45]:
# CPU
tensor_cpu = torch.ones(2,2)

# GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [46]:
#GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

## Tensor Operations

#### Resizing Tensor

In [51]:
a =torch.ones(2,2)
print (a)
print (a.size())

tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])


In [58]:
b = a.view(4)
print (b)
print (b.size())

tensor([1., 1., 1., 1.])
torch.Size([4])


#### Element wise addition

In [66]:
a = torch.ones(2,2)
b = torch.ones(2,2)
print (a)
print (b)
c = a + b # or c = torch.add(a,b)
print (c)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])


#### Inplace addition

In [68]:
print (c)
c.add_(a)
print (c)

tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])


#### Element wise subtraction

In [71]:
c = a-b
print (c)

tensor([[0., 0.],
        [0., 0.]])


In [72]:
a.sub(b)
# inplace 
a.sub_(b)

tensor([[0., 0.],
        [0., 0.]])

#### Element wise Multiplication

In [75]:
a = torch.ones(2,2)
b = torch.zeros(2,2)
print (a)
print (b)
c = a*b
print (c)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


In [78]:
# Not in place
print (torch.mul(a,b))
print (a)
# inplace
print (a.mul_(b))
print (a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


#### Tensor Mean

In [80]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [81]:
print ( a.mean(dim=0))

tensor(5.5000)


In [88]:
a = torch.Tensor([ [1,2,3,4,5,6,7,8,9,10], [1,2,3,4,5,6,7,8,9,10] ])

In [90]:
print ( a.mean(dim=1))

tensor([5.5000, 5.5000])


#### Tensor  Standard Deviation

In [92]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.std(dim=0)

tensor(3.0277)