# Variables and Gradients

## Variables
- A variables wraps a tensor
- Allows accumulation of gradients

In [3]:
import torch
from torch.autograd import Variable

In [5]:
a = Variable(torch.ones(2,2), requires_grad=True )
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [6]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [8]:
# Behaves similarly to tensor
b = Variable(torch.ones(2,2), requires_grad=True )
print (a+b)
print (torch.add(a,b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


## Gradients
- Allows calculation of gradients wrt the variable

In [11]:
x = Variable(torch.ones(2), requires_grad=True )
x

tensor([1., 1.], requires_grad=True)

In [12]:
y = 5 * (x +1)**2
y

tensor([20., 20.], grad_fn=<MulBackward>)

In [14]:
o = (1/2)* torch.sum(y)
o

tensor(20., grad_fn=<MulBackward>)

In [15]:
o.backward()

In [16]:
x.grad

tensor([10., 10.])